/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui8;

import com.Dylan.Genetics.Codons;
import com.Dylan.Genetics.CompRevComp;
import com.Dylan.Genetics.DNAorRNASequenceLocator;
import com.Dylan.Genetics.DNAtoRNA;
import com.Dylan.Genetics.FindInGene;
import com.Dylan.Genetics.FASTAFmtr;
import com.Dylan.Genetics.GeneralInfo;
import com.Dylan.Genetics.ProteinSynthesis;
import com.Dylan.Genetics.StartStopFinder;
import com.Dylan.Genetics.fileHandler;
import java.awt.event.ActionListener;
import java.awt.event.ComponentListener;
import java.awt.event.MouseListener;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author Dylan
 */
public class MainWindow extends javax.swing.JFrame implements ActionListener, MouseListener, ComponentListener, WindowListener {
    static FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "FastA and Text", "fasta", "txt");
    static int fastaSeqStartLine = 2;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        
        initComponents();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem(new DefaultEditorKit.CutAction());
        jMenuItem2 = new javax.swing.JMenuItem(new DefaultEditorKit.CopyAction());
        jMenuItem3 = new javax.swing.JMenuItem(new DefaultEditorKit.PasteAction());
        jFileChooser1 = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane28 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton23 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        DNATab = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DNATransDNA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        DNATransRNA = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DNACompBot = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        DNACompTop = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        DNAStartFindOut = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        DNAStartFindIn = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        DNAFull = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        DNASegFindOut = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        DNASeg = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        DNAGenInfoIn = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        DNAGenInfoOut = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        RNATab = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        RNATransTop = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        RNATransBot = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        RNARevTransDNA = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        RNASeg = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        RNAFull = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jScrollPane17 = new javax.swing.JScrollPane();
        RNASegFindOut = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        RNAStartFindIn = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jScrollPane19 = new javax.swing.JScrollPane();
        RNAStartFindOut = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        RNAGenInfoIn = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jScrollPane21 = new javax.swing.JScrollPane();
        RNAGenInfoOut = new javax.swing.JTextArea();
        GeneTab = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane22 = new javax.swing.JScrollPane();
        FastAOut = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        FastAIn = new javax.swing.JTextArea();
        jButton16 = new javax.swing.JButton();
        GeneSequenceStart = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane24 = new javax.swing.JScrollPane();
        GenecDNAmRNAin = new javax.swing.JTextArea();
        jScrollPane25 = new javax.swing.JScrollPane();
        GenecDNAmRNAout = new javax.swing.JTextArea();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jScrollPane26 = new javax.swing.JScrollPane();
        FindInGeneGene = new javax.swing.JTextArea();
        jScrollPane27 = new javax.swing.JScrollPane();
        FindInGenecDNA = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();

        jPopupMenu1.setMaximumSize(new java.awt.Dimension(50, 200));
        jPopupMenu1.setMinimumSize(new java.awt.Dimension(50, 200));
        jPopupMenu1.addMouseListener(this);

        jMenuItem1.setText("Cut");
        jMenuItem1.addActionListener(this);
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Copy");
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("Paste");
        jPopupMenu1.add(jMenuItem3);

        jFileChooser1.setFileFilter(filter);

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel19.setText("Incorrect File");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel19)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel19)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jDialog2.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog2.setResizable(false);
        jDialog2.addComponentListener(this);

        jScrollPane28.setMinimumSize(new java.awt.Dimension(300, 200));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("When using don't worry about line breaks, spaces, or tabs in the sequence The program will automatically take them out.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane28.setViewportView(jTextArea1);

        jButton23.setText("OK");
        jButton23.addActionListener(this);

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Genetics");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        addWindowListener(this);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel1.addMouseListener(this);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        DNATab.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        DNATransDNA.setColumns(20);
        DNATransDNA.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DNATransDNA.setLineWrap(true);
        DNATransDNA.setRows(5);
        DNATransDNA.addMouseListener(this);
        jScrollPane1.setViewportView(DNATransDNA);

        DNATransRNA.setColumns(20);
        DNATransRNA.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DNATransRNA.setLineWrap(true);
        DNATransRNA.setRows(5);
        DNATransRNA.addMouseListener(this);
        jScrollPane2.setViewportView(DNATransRNA);

        jButton1.setText("Transcribe");
        jButton1.addActionListener(this);

        jLabel1.setText("DNA");

        jLabel2.setText("RNA");

        DNACompBot.setColumns(20);
        DNACompBot.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DNACompBot.setLineWrap(true);
        DNACompBot.setRows(5);
        DNACompBot.addMouseListener(this);
        jScrollPane3.setViewportView(DNACompBot);

        DNACompTop.setColumns(20);
        DNACompTop.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DNACompTop.setLineWrap(true);
        DNACompTop.setRows(5);
        DNACompTop.addMouseListener(this);
        jScrollPane4.setViewportView(DNACompTop);

        jButton2.setText("Complementary");
        jButton2.addActionListener(this);

        jButton3.setText("Reverse Complementary");
        jButton3.addActionListener(this);

        jLabel3.setText("DNA");

        jLabel4.setText("DNA'");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(104, 104, 104))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        DNATab.addTab("Transcription/Complementary", jPanel3);

        jPanel4.addMouseListener(this);

        DNAStartFindOut.setColumns(20);
        DNAStartFindOut.setLineWrap(true);
        DNAStartFindOut.setRows(5);
        DNAStartFindOut.addMouseListener(this);
        jScrollPane5.setViewportView(DNAStartFindOut);

        DNAStartFindIn.setColumns(20);
        DNAStartFindIn.setLineWrap(true);
        DNAStartFindIn.setRows(5);
        DNAStartFindIn.setInheritsPopupMenu(true);
        DNAStartFindIn.addMouseListener(this);
        jScrollPane6.setViewportView(DNAStartFindIn);

        jButton4.setText("Find Starts");
        jButton4.addActionListener(this);

        jButton5.setText("Find Stops");
        jButton5.addActionListener(this);

        jButton6.setText(" Find Both ");
        jButton6.addActionListener(this);

        jLabel8.setText("DNA");

        jLabel9.setText("Output");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(152, 152, 152))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DNATab.addTab("Start/Stop Finder", jPanel4);

        DNAFull.setColumns(20);
        DNAFull.setLineWrap(true);
        DNAFull.setRows(5);
        DNAFull.addMouseListener(this);
        jScrollPane7.setViewportView(DNAFull);

        DNASegFindOut.setColumns(20);
        DNASegFindOut.setLineWrap(true);
        DNASegFindOut.setRows(5);
        DNASegFindOut.addMouseListener(this);
        jScrollPane8.setViewportView(DNASegFindOut);

        jButton7.setText("Find It");
        jButton7.addActionListener(this);

        DNASeg.setColumns(20);
        DNASeg.setLineWrap(true);
        DNASeg.setRows(5);
        DNASeg.addMouseListener(this);
        jScrollPane9.setViewportView(DNASeg);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Segment");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Full DNA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(jScrollPane9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(66, 66, 66))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(241, 241, 241))
        );

        DNATab.addTab("Segment Finder", jPanel5);

        DNAGenInfoIn.setColumns(20);
        DNAGenInfoIn.setLineWrap(true);
        DNAGenInfoIn.setRows(5);
        DNAGenInfoIn.addMouseListener(this);
        jScrollPane10.setViewportView(DNAGenInfoIn);

        DNAGenInfoOut.setColumns(20);
        DNAGenInfoOut.setLineWrap(true);
        DNAGenInfoOut.setRows(5);
        DNAGenInfoOut.addMouseListener(this);
        jScrollPane11.setViewportView(DNAGenInfoOut);

        jLabel7.setText("Input DNA Sequence");

        jButton8.setText("Get General Information");
        jButton8.addActionListener(this);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(33, 33, 33)))
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jButton8)))
                .addContainerGap())
            .addComponent(jScrollPane11)
        );

        DNATab.addTab("General Info", jPanel6);

        jTabbedPane1.addTab("DNA", DNATab);

        RNATab.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        RNATransTop.setColumns(20);
        RNATransTop.setLineWrap(true);
        RNATransTop.setRows(5);
        RNATransTop.addMouseListener(this);
        jScrollPane12.setViewportView(RNATransTop);

        RNATransBot.setColumns(20);
        RNATransBot.setLineWrap(true);
        RNATransBot.setRows(5);
        RNATransBot.addMouseListener(this);
        jScrollPane13.setViewportView(RNATransBot);

        jLabel10.setText("RNA");

        jLabel11.setText("Translation");

        jButton9.setText("Translate");
        jButton9.addActionListener(this);

        RNARevTransDNA.setColumns(20);
        RNARevTransDNA.setLineWrap(true);
        RNARevTransDNA.setRows(5);
        RNARevTransDNA.addMouseListener(this);
        jScrollPane14.setViewportView(RNARevTransDNA);

        jLabel12.setText("cDNA");

        jButton10.setText("Rev Trans");
        jButton10.addActionListener(this);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addComponent(jScrollPane12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(17, 17, 17)
                                .addComponent(jButton10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton9)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jButton10)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton9)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(104, 104, 104))))
        );

        RNATab.addTab("Translation/Reverse Transcription", jPanel7);

        RNASeg.setColumns(20);
        RNASeg.setLineWrap(true);
        RNASeg.setRows(5);
        RNASeg.addMouseListener(this);
        jScrollPane15.setViewportView(RNASeg);

        RNAFull.setColumns(20);
        RNAFull.setLineWrap(true);
        RNAFull.setRows(5);
        RNAFull.addMouseListener(this);
        jScrollPane16.setViewportView(RNAFull);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Full RNA");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Segment");

        jButton11.setText("Find It");
        jButton11.addActionListener(this);

        RNASegFindOut.setColumns(20);
        RNASegFindOut.setLineWrap(true);
        RNASegFindOut.setRows(5);
        RNASegFindOut.addMouseListener(this);
        jScrollPane17.setViewportView(RNASegFindOut);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(jScrollPane15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jButton11)
                        .addGap(66, 66, 66))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane17))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(241, 241, 241))
        );

        RNATab.addTab("Segment Finder", jPanel8);

        RNAStartFindIn.setColumns(20);
        RNAStartFindIn.setLineWrap(true);
        RNAStartFindIn.setRows(5);
        RNAStartFindIn.setInheritsPopupMenu(true);
        RNAStartFindIn.addMouseListener(this);
        jScrollPane18.setViewportView(RNAStartFindIn);

        jLabel15.setText("RNA");

        jButton12.setText("Find Starts");
        jButton12.addActionListener(this);

        jButton13.setText("Find Stops");
        jButton13.addActionListener(this);

        jButton14.setText(" Find Both ");
        jButton14.addActionListener(this);

        RNAStartFindOut.setColumns(20);
        RNAStartFindOut.setLineWrap(true);
        RNAStartFindOut.setRows(5);
        RNAStartFindOut.addMouseListener(this);
        jScrollPane19.setViewportView(RNAStartFindOut);

        jLabel16.setText("Output");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12)
                    .addComponent(jButton13)
                    .addComponent(jButton14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(152, 152, 152))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RNATab.addTab("Start/Stop Finder", jPanel9);

        RNAGenInfoIn.setColumns(20);
        RNAGenInfoIn.setLineWrap(true);
        RNAGenInfoIn.setRows(5);
        RNAGenInfoIn.addMouseListener(this);
        jScrollPane20.setViewportView(RNAGenInfoIn);

        jLabel17.setText("Input RNA Sequence");

        jButton15.setText("Get General Information");
        jButton15.addActionListener(this);

        RNAGenInfoOut.setColumns(20);
        RNAGenInfoOut.setLineWrap(true);
        RNAGenInfoOut.setRows(5);
        RNAGenInfoOut.addMouseListener(this);
        jScrollPane21.setViewportView(RNAGenInfoOut);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jButton15)
                        .addGap(33, 33, 33)))
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jButton15)))
                .addContainerGap())
            .addComponent(jScrollPane21)
        );

        RNATab.addTab("General Info", jPanel10);

        jTabbedPane1.addTab("RNA", RNATab);

        GeneTab.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        FastAOut.setColumns(20);
        FastAOut.setLineWrap(true);
        FastAOut.setRows(5);
        FastAOut.addMouseListener(this);
        jScrollPane22.setViewportView(FastAOut);

        FastAIn.setColumns(20);
        FastAIn.setLineWrap(true);
        FastAIn.setRows(5);
        FastAIn.setText("Copy and paste or Select a File");
        FastAIn.addMouseListener(this);
        jScrollPane23.setViewportView(FastAIn);

        jButton16.setText("Select File");
        jButton16.addActionListener(this);

        GeneSequenceStart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        GeneSequenceStart.setSelectedIndex(1);
        GeneSequenceStart.addActionListener(this);

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setText("Sequence Starts on line:");

        jButton17.setText("Get FastA Info");
        jButton17.addActionListener(this);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GeneSequenceStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)))
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane22))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton16)
                            .addComponent(GeneSequenceStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane23, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(jButton17)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        GeneTab.addTab("FastA to Text", jPanel11);

        GenecDNAmRNAin.setColumns(20);
        GenecDNAmRNAin.setLineWrap(true);
        GenecDNAmRNAin.setRows(5);
        GenecDNAmRNAin.addMouseListener(this);
        jScrollPane24.setViewportView(GenecDNAmRNAin);

        GenecDNAmRNAout.setColumns(20);
        GenecDNAmRNAout.setLineWrap(true);
        GenecDNAmRNAout.setRows(5);
        GenecDNAmRNAout.addMouseListener(this);
        jScrollPane25.setViewportView(GenecDNAmRNAout);

        jButton18.setText("mRNA to cDNA");
        jButton18.addActionListener(this);

        jButton19.setText("cDNA to mRNA");
        jButton19.addActionListener(this);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton18)
                    .addComponent(jButton19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane25)
                    .addComponent(jScrollPane24))
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jButton18)
                .addGap(31, 31, 31)
                .addComponent(jButton19)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        GeneTab.addTab("cDNA and mRNA", jPanel12);

        jButton20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton20.setText("Find in Gene");
        jButton20.addActionListener(this);

        FindInGeneGene.setColumns(20);
        FindInGeneGene.setLineWrap(true);
        FindInGeneGene.setRows(5);
        FindInGeneGene.addMouseListener(this);
        jScrollPane26.setViewportView(FindInGeneGene);

        FindInGenecDNA.setColumns(20);
        FindInGenecDNA.setLineWrap(true);
        FindInGenecDNA.setRows(5);
        FindInGenecDNA.addMouseListener(this);
        jScrollPane27.setViewportView(FindInGenecDNA);

        jLabel21.setText("cDNA");

        jLabel22.setText("Gene");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setText("Will create a .doc file at the location of this ");

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel23.setText("program. Introns are red exons are blue.");

        jButton21.setText("Select File");
        jButton21.addActionListener(this);

        jButton22.setText("Select File");
        jButton22.addActionListener(this);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane27, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(jScrollPane26)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel22)))
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel20))
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jButton22)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jButton21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton20)
                                .addGap(218, 218, 218))))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap(118, Short.MAX_VALUE)
                        .addComponent(jButton21)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton22)
                                .addGap(117, 117, 117))))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(jButton20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        GeneTab.addTab("Find In Gene", jPanel14);

        jTabbedPane1.addTab("Gene", GeneTab);

        jPanel1.add(jTabbedPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jButton1) {
            MainWindow.this.jButton1ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton2) {
            MainWindow.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton3) {
            MainWindow.this.jButton3ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton4) {
            MainWindow.this.jButton4ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton5) {
            MainWindow.this.jButton5ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton6) {
            MainWindow.this.jButton6ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton7) {
            MainWindow.this.jButton7ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton8) {
            MainWindow.this.jButton8ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton9) {
            MainWindow.this.jButton9ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton10) {
            MainWindow.this.jButton10ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton11) {
            MainWindow.this.jButton11ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton12) {
            MainWindow.this.jButton12ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton13) {
            MainWindow.this.jButton13ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton14) {
            MainWindow.this.jButton14ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton15) {
            MainWindow.this.jButton15ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton20) {
            MainWindow.this.jButton20ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton19) {
            MainWindow.this.jButton19ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton18) {
            MainWindow.this.jButton18ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton17) {
            MainWindow.this.jButton17ActionPerformed(evt);
        }
        else if (evt.getSource() == GeneSequenceStart) {
            MainWindow.this.GeneSequenceStartActionPerformed(evt);
        }
        else if (evt.getSource() == jButton16) {
            MainWindow.this.jButton16ActionPerformed(evt);
        }
        else if (evt.getSource() == jMenuItem1) {
            MainWindow.this.jMenuItem1ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton21) {
            MainWindow.this.jButton21ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton22) {
            MainWindow.this.jButton22ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton23) {
            MainWindow.this.jButton23ActionPerformed(evt);
        }
    }

    public void componentHidden(java.awt.event.ComponentEvent evt) {
    }

    public void componentMoved(java.awt.event.ComponentEvent evt) {
    }

    public void componentResized(java.awt.event.ComponentEvent evt) {
    }

    public void componentShown(java.awt.event.ComponentEvent evt) {
        if (evt.getSource() == jDialog2) {
            MainWindow.this.jDialog2ComponentShown(evt);
        }
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jPanel4) {
            MainWindow.this.jPanel4MousePressed(evt);
        }
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jPanel1) {
            MainWindow.this.jPanel1MouseReleased(evt);
        }
        else if (evt.getSource() == DNATransDNA) {
            MainWindow.this.DNATransDNAMouseReleased(evt);
        }
        else if (evt.getSource() == DNATransRNA) {
            MainWindow.this.DNATransRNAMouseReleased(evt);
        }
        else if (evt.getSource() == DNACompBot) {
            MainWindow.this.DNACompBotMouseReleased(evt);
        }
        else if (evt.getSource() == DNACompTop) {
            MainWindow.this.DNACompTopMouseReleased(evt);
        }
        else if (evt.getSource() == jPanel4) {
            MainWindow.this.jPanel4MouseReleased(evt);
        }
        else if (evt.getSource() == DNAStartFindOut) {
            MainWindow.this.DNAStartFindOutMouseReleased(evt);
        }
        else if (evt.getSource() == DNAStartFindIn) {
            MainWindow.this.DNAStartFindInMouseReleased(evt);
        }
        else if (evt.getSource() == DNAFull) {
            MainWindow.this.DNAFullMouseReleased(evt);
        }
        else if (evt.getSource() == DNASegFindOut) {
            MainWindow.this.DNASegFindOutMouseReleased(evt);
        }
        else if (evt.getSource() == DNASeg) {
            MainWindow.this.DNASegMouseReleased(evt);
        }
        else if (evt.getSource() == DNAGenInfoIn) {
            MainWindow.this.DNAGenInfoInMouseReleased(evt);
        }
        else if (evt.getSource() == DNAGenInfoOut) {
            MainWindow.this.DNAGenInfoOutMouseReleased(evt);
        }
        else if (evt.getSource() == RNATransTop) {
            MainWindow.this.RNATransTopMouseReleased(evt);
        }
        else if (evt.getSource() == RNATransBot) {
            MainWindow.this.RNATransBotMouseReleased(evt);
        }
        else if (evt.getSource() == RNARevTransDNA) {
            MainWindow.this.RNARevTransDNAMouseReleased(evt);
        }
        else if (evt.getSource() == RNASeg) {
            MainWindow.this.RNASegMouseReleased(evt);
        }
        else if (evt.getSource() == RNAFull) {
            MainWindow.this.RNAFullMouseReleased(evt);
        }
        else if (evt.getSource() == RNASegFindOut) {
            MainWindow.this.RNASegFindOutMouseReleased(evt);
        }
        else if (evt.getSource() == RNAStartFindIn) {
            MainWindow.this.RNAStartFindInMouseReleased(evt);
        }
        else if (evt.getSource() == RNAStartFindOut) {
            MainWindow.this.RNAStartFindOutMouseReleased(evt);
        }
        else if (evt.getSource() == RNAGenInfoIn) {
            MainWindow.this.RNAGenInfoInMouseReleased(evt);
        }
        else if (evt.getSource() == RNAGenInfoOut) {
            MainWindow.this.RNAGenInfoOutMouseReleased(evt);
        }
        else if (evt.getSource() == jPopupMenu1) {
            MainWindow.this.jPopupMenu1MouseReleased(evt);
        }
        else if (evt.getSource() == FastAIn) {
            MainWindow.this.FastAInMouseReleased(evt);
        }
        else if (evt.getSource() == FastAOut) {
            MainWindow.this.FastAOutMouseReleased(evt);
        }
        else if (evt.getSource() == GenecDNAmRNAin) {
            MainWindow.this.GenecDNAmRNAinMouseReleased(evt);
        }
        else if (evt.getSource() == GenecDNAmRNAout) {
            MainWindow.this.GenecDNAmRNAoutMouseReleased(evt);
        }
        else if (evt.getSource() == FindInGenecDNA) {
            MainWindow.this.FindInGenecDNAMouseReleased(evt);
        }
        else if (evt.getSource() == FindInGeneGene) {
            MainWindow.this.FindInGeneGeneMouseReleased(evt);
        }
    }

    public void windowActivated(java.awt.event.WindowEvent evt) {
    }

    public void windowClosed(java.awt.event.WindowEvent evt) {
    }

    public void windowClosing(java.awt.event.WindowEvent evt) {
    }

    public void windowDeactivated(java.awt.event.WindowEvent evt) {
    }

    public void windowDeiconified(java.awt.event.WindowEvent evt) {
    }

    public void windowIconified(java.awt.event.WindowEvent evt) {
    }

    public void windowOpened(java.awt.event.WindowEvent evt) {
        if (evt.getSource() == MainWindow.this) {
            MainWindow.this.formWindowOpened(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DNATransRNA.setText(DNAtoRNA.DTR(DNATransDNA.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DNACompBot.setText(CompRevComp.complementary(DNACompTop.getText()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DNACompBot.setText(CompRevComp.complementReverse(DNACompTop.getText()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DNAStartFindOut.setText(StartStopFinder.StartAndStopFinder(Codons.FindCondons(DNAStartFindIn.getText())));
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DNAStartFindOut.setText(StartStopFinder.StartFinder(Codons.FindCondons(DNAStartFindIn.getText())));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DNAStartFindOut.setText(StartStopFinder.StopFinder(Codons.FindCondons(DNAStartFindIn.getText())));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
     
          
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseReleased
                     
    }//GEN-LAST:event_jPanel4MouseReleased

    private void jPopupMenu1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPopupMenu1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPopupMenu1MouseReleased

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        
    }//GEN-LAST:event_jPanel1MouseReleased

    private void DNAStartFindInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNAStartFindInMouseReleased
        popup(evt);
    }//GEN-LAST:event_DNAStartFindInMouseReleased

    private void DNAStartFindOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNAStartFindOutMouseReleased
        popup(evt);
    }//GEN-LAST:event_DNAStartFindOutMouseReleased

    private void DNATransDNAMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNATransDNAMouseReleased
        popup(evt);
    }//GEN-LAST:event_DNATransDNAMouseReleased

    private void DNATransRNAMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNATransRNAMouseReleased
        popup(evt);
    }//GEN-LAST:event_DNATransRNAMouseReleased

    private void DNACompBotMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNACompBotMouseReleased
        popup(evt);
    }//GEN-LAST:event_DNACompBotMouseReleased

    private void DNACompTopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNACompTopMouseReleased
        popup(evt);
    }//GEN-LAST:event_DNACompTopMouseReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        DNASegFindOut.setText(DNAorRNASequenceLocator.scanString(DNAFull.getText(), DNASeg.getText()));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DNAGenInfoOut.setText(GeneralInfo.generalInfo(DNAGenInfoIn.getText(), "DNA"));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void DNAGenInfoInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNAGenInfoInMouseReleased
       popup(evt);
    }//GEN-LAST:event_DNAGenInfoInMouseReleased

    private void DNAGenInfoOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNAGenInfoOutMouseReleased
        popup(evt);
    }//GEN-LAST:event_DNAGenInfoOutMouseReleased

    private void DNASegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNASegMouseReleased
        popup(evt);
    }//GEN-LAST:event_DNASegMouseReleased

    private void DNAFullMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNAFullMouseReleased
        popup(evt);
    }//GEN-LAST:event_DNAFullMouseReleased

    private void DNASegFindOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNASegFindOutMouseReleased
       popup(evt);
    }//GEN-LAST:event_DNASegFindOutMouseReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        RNATransBot.setText(ProteinSynthesis.RNASyn(Codons.FindCondons(RNATransTop.getText())));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        RNARevTransDNA.setText(DNAtoRNA.RTD(RNATransTop.getText()));
    }//GEN-LAST:event_jButton10ActionPerformed

    private void RNASegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RNASegMouseReleased
        popup(evt);
    }//GEN-LAST:event_RNASegMouseReleased

    private void RNAFullMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RNAFullMouseReleased
        popup(evt);
    }//GEN-LAST:event_RNAFullMouseReleased

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        RNASegFindOut.setText(DNAorRNASequenceLocator.scanString(RNAFull.getText(), RNASeg.getText()));
    }//GEN-LAST:event_jButton11ActionPerformed

    private void RNASegFindOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RNASegFindOutMouseReleased
       popup(evt);
    }//GEN-LAST:event_RNASegFindOutMouseReleased

    private void RNAStartFindInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RNAStartFindInMouseReleased
        popup(evt);
    }//GEN-LAST:event_RNAStartFindInMouseReleased

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        RNAStartFindOut.setText(StartStopFinder.StartFinder(Codons.FindCondons(RNAStartFindIn.getText())));
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        RNAStartFindOut.setText(StartStopFinder.StopFinder(Codons.FindCondons(RNAStartFindIn.getText())));
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        RNAStartFindOut.setText(StartStopFinder.StartAndStopFinder(Codons.FindCondons(RNAStartFindIn.getText())));
    }//GEN-LAST:event_jButton14ActionPerformed

    private void RNAStartFindOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RNAStartFindOutMouseReleased
        popup(evt);
    }//GEN-LAST:event_RNAStartFindOutMouseReleased

    private void RNAGenInfoInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RNAGenInfoInMouseReleased
        popup(evt);
    }//GEN-LAST:event_RNAGenInfoInMouseReleased

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        RNAGenInfoOut.setText(GeneralInfo.generalInfo(RNAGenInfoIn.getText(), "RNA"));
    }//GEN-LAST:event_jButton15ActionPerformed

    private void RNAGenInfoOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RNAGenInfoOutMouseReleased
        popup(evt);
    }//GEN-LAST:event_RNAGenInfoOutMouseReleased

    private void RNATransTopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RNATransTopMouseReleased
        popup(evt);
    }//GEN-LAST:event_RNATransTopMouseReleased

    private void RNATransBotMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RNATransBotMouseReleased
        popup(evt);
    }//GEN-LAST:event_RNATransBotMouseReleased

    private void RNARevTransDNAMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RNARevTransDNAMouseReleased
        popup(evt);
    }//GEN-LAST:event_RNARevTransDNAMouseReleased

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        try {
            FindInGene.gogo(FindInGenecDNA.getText(), FindInGeneGene.getText());
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        GenecDNAmRNAout.setText(DNAtoRNA.DTR(GenecDNAmRNAin.getText()));
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        GenecDNAmRNAout.setText(DNAtoRNA.RTD(GenecDNAmRNAin.getText()));
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        FastAOut.setText(FASTAFmtr.getFastA(FastAIn.getText(), fastaSeqStartLine));
    }//GEN-LAST:event_jButton17ActionPerformed

    private void GeneSequenceStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneSequenceStartActionPerformed
        fastaSeqStartLine = GeneSequenceStart.getSelectedIndex() + 1;
    }//GEN-LAST:event_GeneSequenceStartActionPerformed

    @SuppressWarnings("deprecation")
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        jFileChooser1.showDialog(jFileChooser1, "Choose File");
        try {
            FastAIn.setText(fileHandler.readFile(jFileChooser1.getSelectedFile().getAbsolutePath()));
        } catch (IOException ex) {
            jDialog1.show();
        }
        try {
            FastAOut.setText(FASTAFmtr.getFastA(fileHandler.readFile(jFileChooser1.getSelectedFile().getAbsolutePath()), fastaSeqStartLine));
        } catch (IOException ex) {
            jDialog1.show();
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void FastAInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FastAInMouseReleased
        popup(evt);
    }//GEN-LAST:event_FastAInMouseReleased

    private void FastAOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FastAOutMouseReleased
        popup(evt);
    }//GEN-LAST:event_FastAOutMouseReleased

    private void GenecDNAmRNAinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenecDNAmRNAinMouseReleased
        popup(evt);
    }//GEN-LAST:event_GenecDNAmRNAinMouseReleased

    private void GenecDNAmRNAoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenecDNAmRNAoutMouseReleased
        popup(evt);
    }//GEN-LAST:event_GenecDNAmRNAoutMouseReleased

    private void FindInGenecDNAMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindInGenecDNAMouseReleased
        popup(evt);
    }//GEN-LAST:event_FindInGenecDNAMouseReleased

    private void FindInGeneGeneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindInGeneGeneMouseReleased
        popup(evt);
    }//GEN-LAST:event_FindInGeneGeneMouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                    
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        jFileChooser1.showDialog(jFileChooser1, "Choose File");
        try {
            FindInGenecDNA.setText(fileHandler.readFile(jFileChooser1.getSelectedFile().getAbsolutePath()));
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        jFileChooser1.showDialog(jFileChooser1, "Choose File");
        try {
            FindInGeneGene.setText(fileHandler.readFile(jFileChooser1.getSelectedFile().getAbsolutePath()));
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        jDialog2.dispose();
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jDialog2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDialog2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialog2ComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jDialog2.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

        
    public void popup(java.awt.event.MouseEvent e){
         if (e.isPopupTrigger()) {
            jPopupMenu1.show(e.getComponent(),
                       e.getX(), e.getY());
    }
    }
    
  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea DNACompBot;
    public javax.swing.JTextArea DNACompTop;
    public javax.swing.JTextArea DNAFull;
    public javax.swing.JTextArea DNAGenInfoIn;
    public javax.swing.JTextArea DNAGenInfoOut;
    public javax.swing.JTextArea DNASeg;
    public javax.swing.JTextArea DNASegFindOut;
    public javax.swing.JTextArea DNAStartFindIn;
    public javax.swing.JTextArea DNAStartFindOut;
    public javax.swing.JTabbedPane DNATab;
    public javax.swing.JTextArea DNATransDNA;
    public javax.swing.JTextArea DNATransRNA;
    public javax.swing.JTextArea FastAIn;
    public javax.swing.JTextArea FastAOut;
    public javax.swing.JTextArea FindInGeneGene;
    public javax.swing.JTextArea FindInGenecDNA;
    public javax.swing.JComboBox GeneSequenceStart;
    public javax.swing.JTabbedPane GeneTab;
    public javax.swing.JTextArea GenecDNAmRNAin;
    public javax.swing.JTextArea GenecDNAmRNAout;
    public javax.swing.JTextArea RNAFull;
    public javax.swing.JTextArea RNAGenInfoIn;
    public javax.swing.JTextArea RNAGenInfoOut;
    public javax.swing.JTextArea RNARevTransDNA;
    public javax.swing.JTextArea RNASeg;
    public javax.swing.JTextArea RNASegFindOut;
    public javax.swing.JTextArea RNAStartFindIn;
    public javax.swing.JTextArea RNAStartFindOut;
    public javax.swing.JTabbedPane RNATab;
    public javax.swing.JTextArea RNATransBot;
    public javax.swing.JTextArea RNATransTop;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton10;
    public javax.swing.JButton jButton11;
    public javax.swing.JButton jButton12;
    public javax.swing.JButton jButton13;
    public javax.swing.JButton jButton14;
    public javax.swing.JButton jButton15;
    public javax.swing.JButton jButton16;
    public javax.swing.JButton jButton17;
    public javax.swing.JButton jButton18;
    public javax.swing.JButton jButton19;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton20;
    public javax.swing.JButton jButton21;
    public javax.swing.JButton jButton22;
    public javax.swing.JButton jButton23;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    public javax.swing.JButton jButton9;
    public javax.swing.JDialog jDialog1;
    public javax.swing.JDialog jDialog2;
    public javax.swing.JFileChooser jFileChooser1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel10;
    public javax.swing.JPanel jPanel11;
    public javax.swing.JPanel jPanel12;
    public javax.swing.JPanel jPanel14;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    public javax.swing.JPanel jPanel9;
    public javax.swing.JPopupMenu jPopupMenu1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane10;
    public javax.swing.JScrollPane jScrollPane11;
    public javax.swing.JScrollPane jScrollPane12;
    public javax.swing.JScrollPane jScrollPane13;
    public javax.swing.JScrollPane jScrollPane14;
    public javax.swing.JScrollPane jScrollPane15;
    public javax.swing.JScrollPane jScrollPane16;
    public javax.swing.JScrollPane jScrollPane17;
    public javax.swing.JScrollPane jScrollPane18;
    public javax.swing.JScrollPane jScrollPane19;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane20;
    public javax.swing.JScrollPane jScrollPane21;
    public javax.swing.JScrollPane jScrollPane22;
    public javax.swing.JScrollPane jScrollPane23;
    public javax.swing.JScrollPane jScrollPane24;
    public javax.swing.JScrollPane jScrollPane25;
    public javax.swing.JScrollPane jScrollPane26;
    public javax.swing.JScrollPane jScrollPane27;
    public javax.swing.JScrollPane jScrollPane28;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}